#!/usr/bin/env bash

tmux_attach_fzf() {
    target_sesstion="$(tmux list-sessions | sed -E s/:.*$// | fzf --height 15%)"

    # Check if in Tmux session
    if [ -z "$TMUX" ]; then
        tmux attach -t "${target_sesstion}"
    else 
        # Tmux already has its own session picker, so this may not be used frequently.
        # However, for consistency I might as well include it.
        tmux switch -t "${target_sesstion}"
    fi
}

# Disable the terminal flow control feature.
# This allows me to rebind Control+s and Control+q.
stty -ixon

# Select a tmux session by using an fzf picker.
# The key combination Control + s was chosen, since it roughly corresponds
# the the default Tmux session picker keybind (Control + b followed by s)
bind '"\C-s":"tmux_attach_fzf\n"'
