#!/usr/bin/env bash

fzf_tmux_session() {
    target_sesstion="$(tmux list-sessions | sed -E s/:.*$// | fzf --height 15%)"

    # Check if in Tmux session
    if [ -z "$TMUX" ]; then
        tmux attach -t "${target_sesstion}"
    else 
        # Tmux already has its own session picker, so this may not be used frequently.
        # However, for consistency I might as well include it.
        tmux switch -t "${target_sesstion}"
    fi
}

fzf_git_branch() {
    if git rev-parse --git-dir > /dev/null 2>&1; then
        git branch | sed -r 's/[* ]+//' | fzf --height=40% | xargs -I{} git checkout {}
    else
        echo "not a git repo, cannot select branch"
    fi
}

# Disable the terminal flow control feature.
# This allows me to rebind Control+s and Control+q.
stty -ixon

# Select a tmux session by using an fzf picker.
# The key combination Control + s was chosen, since it roughly corresponds
# the the default Tmux session picker keybind (Control + b followed by s)
bind '"\C-s":"fzf_tmux_session\n"'

# Select a tmux session by using an fzf picker.
# The keybind Control + q is arbitrary (may be switched in the future).
bind '"\C-q":"fzf_git_branch\n"'
